---
 - name: create default site configurations 
   copy: src=default.conf dest=/etc/nginx/conf.d/default.conf mode=0644
   notify: 
    - restart nginx service
 - name: create home page for default site
   copy: src=index.html dest=/usr/share/nginx/html/index.html

