---
 - name: create default site configurations 
   template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf mode=0644
   notify: 
    - restart nginx service
 - name: create home page for default site
   copy: src=index.html dest=/usr/share/nginx/html/index.html

 - name: create php virtual hosts
   template:
     src: php_vhost.j2 
     dest: /etc/nginx/conf.d/{{ item.key }}.conf
   with_dict: "{{ nginx['phpsites'] }}"
   notify: 
     - restart nginx service
